### PR TITLE
Updating all resources to use HTTPS.

### PR DESCRIPTION
**Pull request by stephan-nordnes-eriksen**
Love the gem, it is really handy, but I noticed that it sometimes uses http and not https even when the server is running over https. 

For most people this might not be a problem, but for me it ruins my beautiful green lock in the url of my webpage.

I found a quick patch which was to simply use https by default. I have not found any instance where this does not work, but it can be smart to verify that all works as advertised.

Keep up the good work :)

### CODE REVIEW

**Comment by hermango** [comment]
Hi Stephan, 

Thank you for your great additions. These all seem to work. I may change the script partial for tumblr to use relative protocol instead (like contributor [@trungpham](https://github.com/trungpham) [did for other buttons](https://github.com/hermango/shareable/commit/00f1303c2c70b90b56246c819857375c9feb77ba))  just to reduce latency wherever possible. Awesome contribution!

**Comment by hermango** [comment]
Stephan, do you include Reddit on your webpage?

I had to change the static link for Reddit back to using http because the web certificate for https://www.reddit.com is invalid. Getting a "host name mismatch" error. Apparently Reddit is still working on it From their admin:

> "We're working on it. As a lot of you have pointed out, https://pay.reddit.com exists but we really don't recommend using it for general browsing because it's slower and still not properly secure."

[His full answer](http://www.reddit.com/r/AskReddit/comments/pz5kx/reddit_y_u_no_ssl/c3thvhd) from 2 years ago.

**Comment by hermango** [comment]
Ack! Ok never mind. Changed Reddit static link back to https. It's using url https://ssl.reddit.com/ now based on this [fix](https://github.com/reddit/reddit/commit/f6aaf4a13d1f30288790d15328a651ccc03b80e0) from their repo.

**Comment by stephan-nordnes-eriksen** [comment]
Nice :)

**Pull request merged**
